// <auto-generated />
using API_mokymai.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APImokymai.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20221129195017_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("API_mokymai.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Cover")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PublishYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Spainito",
                            Cover = 2,
                            PublishYear = 1900,
                            Title = "Orange"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Spainito",
                            Cover = 2,
                            PublishYear = 1910,
                            Title = "Apple"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Africana",
                            Cover = 2,
                            PublishYear = 1920,
                            Title = "Banana"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Italiano",
                            Cover = 2,
                            PublishYear = 1930,
                            Title = "Grapes"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Germaner",
                            Cover = 2,
                            PublishYear = 1940,
                            Title = "Sausages"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Belaruska",
                            Cover = 2,
                            PublishYear = 1950,
                            Title = "Potatoes"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Belaruska",
                            Cover = 2,
                            PublishYear = 1960,
                            Title = "Tomato"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Lithuanis",
                            Cover = 2,
                            PublishYear = 1970,
                            Title = "Morkos"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Lithuanis",
                            Cover = 2,
                            PublishYear = 1980,
                            Title = "Onions"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Lithuanis",
                            Cover = 2,
                            PublishYear = 1990,
                            Title = "Aguonos"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
